main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path("", views.index, name="index"),
    path("results", views.results, name="results"),
    path("2022", views.info2022, name="info2022"),
    path("2023", views.info2023, name="info2023"),
]

rolphopen/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("main.urls")),
    path("teams/", include("teams.urls")),
    path('admin/', admin.site.urls),
]

teams/urls.py
from django.urls import path

from . import views

app_name = 'teams'
urlpatterns = [
    path("generate", views.generate_teams, name="generate"),
    path("draft", views.draft, name="draft")
]

main/models.py
from django.db import models

# Create your models here.

teams/models.py
from django.db import models

# Create your models here.
class Player(models.Model):
    name = models.CharField(max_length=200)
    unwanted_teammates = models.ManyToManyField("self", blank=True, symmetrical=False)
    def __str__(self):
        return f"{self.name}"


class Team(models.Model):
    players = models.ManyToManyField(Player)
    year = models.IntegerField(default=2024)
    show = models.BooleanField(default=False)

class HCP(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    year = models.IntegerField(default=2024)
    hcp = models.FloatField()

main/views.py
from django.http import HttpResponse
from django.template import loader

from teams.models import Team

def index(request):
    upcoming_teams = Team.objects.filter(year=2024, show=True)
    template = loader.get_template("main/index.html")
    context = {"upcoming_teams": upcoming_teams}
    return HttpResponse(template.render(context, request))


def results(request):
    template = loader.get_template("main/results.html")
    context = {}
    return HttpResponse(template.render(context, request))


def info2022(request):
    template = loader.get_template("main/year2022.html")
    context = {}
    return HttpResponse(template.render(context, request))


def info2023(request):
    template = loader.get_template("main/year2023.html")
    context = {}
    return HttpResponse(template.render(context, request))

teams/views.py
import random
import os

from django.http import HttpResponse
from django.template import loader
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Team, Player


def try_generate_teams():
    teams = []
    players = list(Player.objects.all())
    i = 0
    while players:
        player1_index = random.randrange(len(players))
        player2_index = random.randrange(len(players))
        if player2_index != player1_index and players[player2_index] not in players[player1_index].unwanted_teammates.all() and players[player1_index] not in players[player2_index].unwanted_teammates.all():
            player1 = players[player1_index]
            player2 = players[player2_index]
            players.pop(players.index(player1))
            players.pop(players.index(player2))
            team = Team(year=2024)
            team.save()
            team.players.set([player1, player2])
            teams.append(team)
            i = 0
        else:
            i += 1
        if i == 10:
            print("Failed selection, starting again")
            for team in teams:
                team.delete()
            teams = []
            break
    return teams


# Create your views here.
@login_required
@csrf_exempt
def generate_teams(request):
    if request.method == "POST":
        if 'generate_teams' in request.POST:
            upcoming_teams = Team.objects.filter(year=2024)
            if len(list(upcoming_teams)) > 0:
                messages.add_message(request, messages.INFO, "Teams have already been generated")
            else:
                for team in upcoming_teams:
                    team.delete()
                
                i = 0
                while i < 10:
                    teams = try_generate_teams()
                    if len(teams) > 0:
                        break
                    i += 1
                messages.add_message(request, messages.INFO, "New teams generated")
        elif 'show_next_team' in request.POST:
            upcoming_teams = list(Team.objects.filter(year=2024, show=False))
            if len(upcoming_teams) < 1:
                messages.add_message(request, messages.INFO, "All teams are already shown")
            else:
                upcoming_teams[0].show = True
                upcoming_teams[0].save()
                messages.add_message(request, messages.INFO, "New team shall now be showing")


    template = loader.get_template("teams/generate.html")
    upcoming_teams = Team.objects.filter(year=2024)
    context = {"upcoming_teams": upcoming_teams}
    return HttpResponse(template.render(context, request))

# Create your views here.
def draft(request):
    upcoming_teams = Team.objects.filter(year=2024, show=True)
    template = loader.get_template("teams/draft.html")
    context = {"upcoming_teams": upcoming_teams}
    return HttpResponse(template.render(context, request))

main/templates/main/index.html
{% extends "base.html" %}
{% block title %}
<title>Rolph Open 2023</title>
{% endblock %}
{% block content %}
<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
    <div class="w3-content">
        <div class="w3">
            <h1>Rolph Open 2024</h1>
            <h3>Info</h3>
            <p><b>Plats</b>: <a href="https://ringenas.com/" target=”_blank”>Ringenäs GK, Halmstad</a></p>
            <p><b>Datum</b>: 7 September</p>
            <p><b>Tee times</b>: 10:30, 10:40, 10:50, 11:00</p>
            <p><b>Övrigt</b>:<br/> 
            Middag: kl 19,00<br/>
            Incheckning är kl. 15:00 och utcheckning är kl. 10.00.<br/>
            Frukost serveras mellan kl. 07.00 - 10.00.<br/>
<br/>
            Paketpriset: 2 395:-/pp<br/>
<br/>
            En dygns logi med frukostbuffé, en greenfee för 18 hål på Ringenäs Golfklubb samt<br/>
            en två-rätters middag i en underbar familjär atmosfär.<br/>
            Vi bjuder på välkomstgåva, banguide och hyrvagn.<br/>
            </p>
        </div>
    </div>
</div>
  


<!-- First Grid -->
<div class="w3-row-padding w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3">
      <h1>Regler</h1>
      <br/>
      <h3>Skötselregler</h3>
      <p><b>Kasta klubba</b>: 2 straffslag</p>
      <p><b>Slå klubba i annat än boll aggressivt</b>: 1 straffslag</p>
      <br/>
      <h3>HCP</h3>
      <p>Spelare med lägst spelhandicap multiplicerar sin spelhandicap med 0,5. Spelaren med den högre spelhandicapen multicerar sin spelhandicap med 0,2.</p>
      <br/>
      <h3>Scramble</h3>
      <p>
        Båda spelarna i laget slår ut från varje tee och väljer sedan vilken boll de vill fortsätta med, båda spelarna spelar från det valda läget och väljer vilken boll de fortsätter med ända till hål.
      </p>
      <p>
        Varje lag måste minst ta 1/3 av båda spelarnas utslag från tee. Det vill säga att i det fall ett lag består av 2 spelar måste laget välja minst 6 utlag från lag medlem 1 och 6 utslag från lag medlem 2. De 6 andra tee slagen får laget välja antingen lag medlem 1 eller 2. 
      </p>
      <p>
        I fairway, rough eller bunker får båda spelarna i laget plocka upp sin boll och plasera den inom ett scorekorts avstånd från den boll som teamet har valt. Bollen får inte heller plaseras närmare flaggan. 
      </p>
    </div>

  </div>
</div>


<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3">
      <h1>Lag</h1>
      <br/>
      <div class="w3-container w3-center">
        {% for team in upcoming_teams %}
            {% if forloop.first %}<div class="card-group">{% endif %}
            {% if forloop.counter0|divisibleby:3 and not forloop.first %}</div><div class="card-group">{% endif %}
            <div class="card text-white mb-3" style="max-width: 18rem;">
                <div class="card-header {% if forloop.counter0|divisibleby:2 %}bg-primary {% else %} bg-success {% endif %}">Lag</div>
                <div class="card-body bg-secondary ">
                {% for player in team.players.all %}
                    <p class="card-text">{{ player }}</p>
                {% endfor %}
                </div>
            </div>
            {% if forloop.last %}</div>{% endif %}
        {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

main/templates/main/results.html
{% extends "base.html" %}
{% block title %}
<title>Rolph Open Results</title>
{% endblock %}
{% block content %}
<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
    <div class="w3-content">
        <div class="w3">
            <h1>Resultat Rolph Open 2024</h1>
            <div style="text-align: center;">
                <h2>Vinnare</h2>
                <p>Tommy Olsen & Ted Delin</p>
            </div>
            <img src="./static/img/2024_winner.jpg" style="width: 100%" alt="Winners 2023" />
            <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">Plats</th>
                    <th scope="col">Team</th>
                    <th scope="col">Slag</th>
                    <th scope="col">Resultat</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row"><i class="fa-solid fa-trophy"></i> 1</th>
                    <td>Tommy Olsen & Ted Delin</td>
                    <td>75</td>
                    <td>-8</td>
                  </tr>
                  <tr>
                    <th scope="row">2</th>
                    <td>Sebastian Lundgren & John Carlsson</td>
                    <td>82</td>
                    <td>-8</td>
                  </tr>
                  <tr>
                    <th scope="row">3</th>
                    <td>Tobias Sjöberg & Anton Österlind</td>
                    <td>79</td>
                    <td>-5</td>
                  </tr>
                  <tr>
                    <th scope="row">4</th>
                    <td>Robin Wallborg & Joakim Olsson</td>
                    <td>83</td>
                    <td>-1</td>
                  </tr>
                  <tr>
                    <th scope="row">4</th>
                    <td>Joakim Andersson & Johannes Lyttkens</td>
                    <td>92</td>
                    <td>-1</td>
                  </tr>
                  <tr>
                    <th scope="row">6</th>
                    <td>Joakim Karlsson & Jens Andersson</td>
                    <td>98</td>
                    <td>E</td>
                  </tr>
                  <tr>
                    <th scope="row">7</th>
                    <td>Jesper Brunbäck & Markus Bäckström</td>
                    <td>91</td>
                    <td>+2</td>
                  </tr>
                  <tr>
                    <th scope="row">8</th>
                    <td>Hampus Chenon & Erik Andersson</td>
                    <td>95</td>
                    <td>+3</td>
                  </tr>
                </tbody>
              </table>
        </div>
    </div>
</div>

<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
    <div class="w3-content">
        <div class="w3">
            <h1>Resultat Rolph Open 2023</h1>
            <div style="text-align: center;">
                <h2>Vinnare</h2>
                <p>Joakim Olsson & Viktor Wallborg</p>
            </div>
            <img src="./static/img/2023_winner.jpg" style="width: 100%" alt="Winners 2023" />
            <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">Plats</th>
                    <th scope="col">Team</th>
                    <th scope="col">Slag</th>
                    <th scope="col">Resultat</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row"><i class="fa-solid fa-trophy"></i> 1</th>
                    <td>Joakim Olsson & Viktor Wallborg</td>
                    <td>81</td>
                    <td>-15</td>
                  </tr>
                  <tr>
                    <th scope="row">2</th>
                    <td>Anton Österlind & Viktor Pyk</td>
                    <td>81</td>
                    <td>-14</td>
                  </tr>
                  <tr>
                    <th scope="row">3</th>
                    <td>Ted Delin & Markus Bäckström</td>
                    <td>78</td>
                    <td>-12</td>
                  </tr>
                  <tr>
                    <th scope="row">4</th>
                    <td>Jesper Brunbäck & Joakim Andersson</td>
                    <td>87</td>
                    <td>-9</td>
                  </tr>
                  <tr>
                    <th scope="row">5</th>
                    <td>Tommy Olsen & Johannes Lyttkens</td>
                    <td>85</td>
                    <td>-8</td>
                  </tr>
                  <tr>
                    <th scope="row">6</th>
                    <td>Hampus Chenon & Joakim Karlsson</td>
                    <td>91</td>
                    <td>-6</td>
                  </tr>
                  <tr>
                    <th scope="row">7</th>
                    <td>Robin Wallborg & Semih Yulmaz</td>
                    <td>90</td>
                    <td>-5</td>
                  </tr>
                  <tr>
                    <th scope="row">8</th>
                    <td>Tobias Sjöberg & Erik Andersson</td>
                    <td>97</td>
                    <td>-3</td>
                  </tr>
                </tbody>
              </table>
        </div>
    </div>
</div>

<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
    <div class="w3-content">
        <div class="w3">
            <h1>Resultat Rolph Open 2022</h1>
            <div style="text-align: center;">
                <h2>Vinnare</h2>
                <p>Hampus Chenon & Ted Delin</p>
            </div>
            <img src="./static/img/2022_winner.jpg" style="width: 100%" alt="Winners 2022" />
            <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">Plats</th>
                    <th scope="col">Team</th>
                    <th scope="col">Slag</th>
                    <th scope="col">Resultat</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row"><i class="fa-solid fa-trophy"></i> 1</th>
                    <td>Hampus Chenon & Ted Delin</td>
                    <td>83</td>
                    <td>-1</td>
                  </tr>
                  <tr>
                    <th scope="row">2</th>
                    <td>Jesper Brunbäck & Tommy Olsen</td>
                    <td>86</td>
                    <td>-1</td>
                  </tr>
                  <tr>
                    <th scope="row">3</th>
                    <td>Anton Österlind & Robin Wallborg</td>
                    <td>83</td>
                    <td>E</td>
                  </tr>
                  <tr>
                    <th scope="row">4</th>
                    <td>Joakim Karlsson & Joakim Olsson</td>
                    <td>90</td>
                    <td>+2</td>
                  </tr>
                  <tr>
                    <th scope="row">5</th>
                    <td>Joakim Andersson & Viktor Wallborg</td>
                    <td>108</td>
                    <td>+12</td>
                  </tr>
                  <tr>
                    <th scope="row">6</th>
                    <td>Markus Bäckström & Johannes Lyttkens</td>
                    <td>113</td>
                    <td>+20</td>
                  </tr>
                  <tr>
                    <th scope="row">7</th>
                    <td>Tobias Sjöberg & Sebastian Lundgren</td>
                    <td>110</td>
                    <td>+20</td>
                  </tr>
                </tbody>
              </table>
        </div>
    </div>
</div>
  


<!-- First Grid -->
<div class="w3-row-padding w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3">
        <h1>Resultat Rolph Open 2021</h1>
        <div style="text-align: center;">
            <h2>Vinnare</h2>
            <p>Anton Österlind & Ted Delin</p>
        </div>
        <img src="./static/img/2021_winner.jpg" style="width: 100%" alt="Winners 2021" />
    </div>

  </div>
</div>

<!-- First Grid -->
<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
    <div class="w3-content">
      <div class="w3">
          <h1>Resultat Rolph Open 2020</h1>
          <div style="text-align: center;">
              <h2>Vinnare</h2>
              <p>Robin Wallborg & Tommy Olsen</p>
          </div>
          <img src="./static/img/2020_winner.jpg" style="width: 100%" alt="Winners 2020" />
      </div>
  
    </div>
  </div>

{% endblock %}

main/templates/main/year2022.html
{% extends "base.html" %}
{% block title %}
<title>Rolph Open 2022</title>
{% endblock %}
{% block content %}

<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
    <div class="w3-content">
        <div class="w3">
            <h1>Rolph Open 2022</h1>
            <h3>Info</h3>
            <p><b>Plats</b>: <a href="https://www.sotenasgolf.se/" target=”_blank”>Sotenäs GK</a></p>
            <p><b>Datum</b>: 3 September</p>
            <p><b>Första Tee</b>: 09:50</p>
            <p><b>Övrigt</b>: Glöm inte att gå in till receptionen och registrera dig plus betala!</p>
        </div>
    </div>
</div>
  


<!-- First Grid -->
<div class="w3-row-padding w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3">
      <h1>Regler</h1>
      <br/>
      <h3>Skötselregler</h3>
      <p><b>Kasta klubba</b>: 2 straffslag</p>
      <p><b>Slå klubba i annat än boll aggressivt</b>: 1 straffslag</p>
      <br/>
      <h3>HCP</h3>
      <p>Spelare med lägst spelhandicap multiplicerar sin spelhandicap med 0,5. Spelaren med den högre spelhandicapen multicerar sin spelhandicap med 0,2.</p>
      <br/>
      <h3>Matchspel Scramble</h3>
      <p>
        Båda spelarna i laget slår ut från varje tee och väljer sedan vilken boll de vill fortsätta med, båda spelarna spelar från det valda läget och väljer vilken boll de fortsätter med ända till hål, och hålet kan antingen vinnas, förloras eller bli oavgjord.
      </p>
      <p>
        Varje lag får endast välja samma spelares boll 2 gånger i rad.
      </p>
    </div>

  </div>
</div>


<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3">
      <h1>Lag</h1>
      <br/>
      <div class="w3-container w3-center">
        <div class="card-group">
            <div class="card text-white mb-3" style="max-width: 18rem;">
                <div class="card-header bg-primary">Lag 1</div>
                <div class="card-body bg-secondary">
                <p class="card-text">Sebastian Lundgren</p>
                <p class="card-text">Tobias Sjöberg</p>
                </div>
            </div>
            <div class="card text-white mb-3" style="max-width: 18rem;">
                <div class="card-header bg-success">Lag 2</div>
                <div class="card-body bg-secondary">
                    <p class="card-text">Hampus Chenon</p>
                    <p class="card-text">Ted Delin</p>
                </div>
            </div>
            <div class="card text-white mb-3" style="max-width: 18rem;">
                <div class="card-header bg-danger">Lag 3</div>
                <div class="card-body bg-secondary">
                    <p class="card-text">Johannes Lyttkens</p>
                    <p class="card-text">Markus Bäckström</p>
                </div>
            </div>
        </div>
        <div class="card-group">
            <div class="card text-white mb-3" style="max-width: 18rem;">
                <div class="card-header bg-warning">Lag 4</div>
                <div class="card-body bg-secondary">
                    <p class="card-text">Joakim Andersson</p>
                    <p class="card-text">Viktor Wallborg</p>
                </div>
            </div>
            <div class="card text-white mb-3" style="max-width: 18rem;">
                <div class="card-header bg-info">Lag 5</div>
                <div class="card-body bg-secondary">
                    <p class="card-text">Jesper Brunbäck</p>
                    <p class="card-text">Tommy Olsen</p>
                </div>
            </div>
            <div class="card text-white mb-3" style="max-width: 18rem;">
                <div class="card-header bg-secondary">Lag 6</div>
                <div class="card-body bg-secondary">
                    <p class="card-text">Anton Österlind</p>
                    <p class="card-text">Robin Wallborg</p>
                </div>
            </div>
        </div>
        <div class="card text-white mb-3" style="max-width: 18rem;">
            <div class="card-header bg-dark">Lag 7</div>
            <div class="card-body bg-secondary">
                <p class="card-text">Joakim Karlsson</p>
                <p class="card-text">Joakim Olsson</p>
            </div>
        </div>
      </div>
      <h1>Tee times</h1>
      <br/>
      <div class="w3-container w3-center">
        <div class="card-group">
            <div class="card text-white mb-3" style="max-width: 18rem;">
                <div class="card-header bg-primary">10:00</div>
                <div class="card-body bg-secondary">
                <p class="card-text">Sebastian/Tobias</p>
                <p class="card-text">Joakim K/Joakim O</p>
                </div>
            </div>
            <div class="card text-white mb-3" style="max-width: 18rem;">
                <div class="card-header bg-primary">10:10</div>
                <div class="card-body bg-secondary">
                    <p class="card-text">Tommy/Jesper</p>
                    <p class="card-text">Markus/Johannes</p>
                </div>
            </div>
            <div class="card text-white mb-3" style="max-width: 18rem;">
                <div class="card-header bg-primary">10:20</div>
                <div class="card-body bg-secondary">
                    <p class="card-text">Robin/Anton</p>
                </div>
            </div>
            <div class="card text-white mb-3" style="max-width: 18rem;">
                <div class="card-header bg-primary">10:30</div>
                <div class="card-body bg-secondary">
                    <p class="card-text">Ted/Hampus</p>
                    <p class="card-text">Joakim A/Viktor</p>
                </div>
            </div>
        </div>
    </div>
    </div>
  </div>
</div>
</body>
</html>

{% endblock %}

teams/templates/teams/draft.html
{% extends "base.html" %}
{% block title %}
<title>Rolph Open Team Selection</title>
{% endblock %}
{% block head %}
<meta http-equiv="refresh" content="10">
{% endblock %}
{% block content %}
<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
    <div class="w3-content">
        <div class="w3">
            <h1>Live val av lag 2024</h1>
            <p>Här kommer alla lag slumpmässigt väljas 2024-05-01 13:30</p>
        </div>
    </div>
</div>

<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3">
      <h1>Lag</h1>
      <br/>
      <div class="w3-container w3-center">
        {% for team in upcoming_teams %}
            {% if forloop.first %}<div class="card-group">{% endif %}
            {% if forloop.counter0|divisibleby:3 and not forloop.first %}</div><div class="card-group">{% endif %}
            <div class="card text-white mb-3" style="max-width: 18rem;">
                <div class="card-header bg-primary">Lag</div>
                <div class="card-body bg-secondary">
                {% for player in team.players.all %}
                    <p class="card-text">{{ player }}</p>
                {% endfor %}
                </div>
            </div>
            {% if forloop.last %}</div>{% endif %}
        {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

teams/templates/teams/generate.html
{% extends "base.html" %}
{% block title %}
<title>Rolph Open Team Selection</title>
{% endblock %}
{% block content %}
<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
    <div class="w3-content">
        <div class="w3">
            <h1>Team generation</h1>
            <form action="" method="post">
            <input type="submit" name="generate_teams" value="Slumpa nya team" onclick="return confirm('Vill du verkligen slumpa nya team?');" />
            <input type="submit" name="show_next_team" value="Visa nästa team" />
            </form>
        </div>
    </div>
</div>

<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3">
      <h1>Lag</h1>
      <br/>
      <div class="w3-container w3-center">
        {% for team in upcoming_teams %}
            {% if forloop.first %}<div class="card-group">{% endif %}
            {% if forloop.counter0|divisibleby:3 and not forloop.first %}</div><div class="card-group">{% endif %}
            <div class="card text-white mb-3" style="max-width: 18rem;">
                <div class="card-header {% if team.show %} bg-success{% else %} bg-primary {% endif %}">Lag</div>
                <div class="card-body bg-secondary">
                {% for player in team.players.all %}
                    <p class="card-text">{{ player }}</p>
                {% endfor %}
                </div>
            </div>
            {% if forloop.last %}</div>{% endif %}
        {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}{% endblock %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" type="image/x-icon" href="./static/img/favicon.png">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://kit.fontawesome.com/01e5120672.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<style>
  body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif}
  .w3-bar,h1,button {font-family: "Montserrat", sans-serif}
  .fa-anchor,.fa-coffee {font-size:200px}
  #header {
      background-image: url("{% static 'img/header-mobile.png' %}"); 
      background-repeat: no-repeat; 
      background-size: 100% 100%;
  }
  #logo {
      height: 200px;
  }
  @media only screen and (min-width: 1000px) {
      #header {
          background-image: url("{% static 'img/header.jpg' %}");
          min-height: 560px;
      }
      #logo {
          height: 400px;
      }
  }
  
  /* The container <div> - needed to position the dropdown content */
  .dropdown {
      padding: 0.2em;
    background-color: rgba(0, 0, 0, 0.2);
    position: fixed;
    display: inline-block;
  }
  
  .dropbtn {
      color: rgb(255, 255, 255);
      border: none;
      cursor: pointer;
      padding: 0;
      outline: inherit;
  } 
  
  /* Dropdown Content (Hidden by Default) */
  .dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
  }
  
  /* Links inside the dropdown */
  .dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
  }
  
  /* Change color of dropdown links on hover */
  .dropdown-content a:hover {background-color: #f1f1f1}
  
  /* Show the dropdown menu on hover */
  .dropdown:hover .dropdown-content {
    display: block;
  }
  
  </style>
  {% block head %}{% endblock %}
</head>
<body>
<!-- Header -->
<div class="dropdown">
  <button class="dropbtn fa-solid fa-bars fa-2xl"></button>
  <div class="dropdown-content">
    <a href="{% url 'main:index' %}">2024</a>
    <a href="{% url 'main:info2023' %}">2023</a>
    <a href="{% url 'main:info2022' %}">2022</a>
    <a href="{% url 'main:results' %}">Resultat</a>
    <a href="{% url 'teams:draft' %}">Live Draft</a>
    {% if user.is_authenticated %}
    <a href="{% url 'teams:generate' %}">Team Generation</a>
    {% endif %}
  </div>
</div>
<div id="header">
<header class="w3-container w3-center" style="padding:128px 16px">
  <img id="logo" src="{% static 'img/logo_white_bg.png' %}" alt="Rolph Open Logo"> 
</header>
</div>
{% if messages %}
    {% for message in messages %}
        <p class="text-danger">{{ message }}</p>
    {% endfor %}
{% endif %}
{% block content %}{% endblock %}

</body>
</html>